### PR TITLE
Put padId in URLs

### LINKED ISSUE #2: Sub URLS
PadWiki should use SubUrls for the pads in one Wiki.
The history API could be used to avoid page reloads.

### PR DESCRIPTION
**Pull request by fflorent**
Fixes #2 

Please don't hesitate to nitpick so I can fix it according to your coding style. Thanks!

### CODE REVIEW

**Comment by fflorent** [comment]
@anuejn up?

**Comment by anuejn** [comment]
oh shit sorry for the long delay. i somehow missed it :(
will look into it and test it

**Comment by fflorent** [comment]
Thanks! :)

**Comment by anuejn** [comment]
Very nice, thanks a lot :).
closes #2

**Comment by anuejn** [comment]
also published to npm

**Comment by fflorent** [comment]
Good, thank you! Do you intend to publish a new version on npm soon? We rely on your project and this feature is much awaited :).

Florent

**Comment by fflorent** [comment]
Oops, I somehow missed your last message, sorry! Is it normal that the version number is not incremented in [`package.json`](https://github.com/anuejn/PadWiki/blob/master/package.json#L3)?

**Comment by anuejn** [comment]
ah shit forgot to push :)

**Comment by fflorent** [comment]
Good, thank you :)

**Pull request merged**
